# Generated by Django 5.2.3 on 2025-07-27 01:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_product_id_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=30)),
                ('phone', models.IntegerField(default='', max_length=12)),
                ('desc', models.TextField(default='', max_length=400)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
